# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170501_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shoppingCarts',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
